config/routes.rb
Newapp::Application.routes.draw do

  resources :microposts, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: "static_pages#home"
  get "help",to:"static_pages#help"
  get "about",to:"static_pages#about"
  get "contact",to:"static_pages#contact"
  get "signup",to:"users#new"
  get "signin", to:"sessions#new"
  match "/signout",to:"sessions#destroy", via: :delete

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content
  validates :content, length: {maximum: 140,minimum:2} ,presence:true
  validates :user_id, presence:true

  default_scope order: "microposts.created_at DESC"


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user,  only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy
  # GET /microposts
  # GET /microposts.json



  # GET /microposts/1
  # GET /microposts/1.json
  #def show
   # @micropost = Micropost.find(params[:id])


    #respond_to do |format|
    #  format.html # show.html.erb
     # format.json { render json: @micropost }
    #end
  #end

  # GET /microposts/new
  # GET /microposts/new.json
  #def new
   # @micropost = Micropost.new

    #respond_to do |format|
     # format.html # new.html.erb
      #format.json { render json: @micropost }
    #end
  #end

  # GET /microposts/1/edit
 # def edit
  #  @micropost = Micropost.find(params[:id])
  #end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(params[:micropost])

    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items= current_user.feed
        #@feed_items = []
      #render the html of"static_pages/home",did not go through the static_pages controller,get the data only in the current
      #controller
        render 'static_pages/home'

      end
    end


  # PUT /microposts/1
  # PUT /microposts/1.json
  #def update
   # @micropost = Micropost.find(params[:id])

    #respond_to do |format|
     # if @micropost.update_attributes(params[:micropost])
      #  format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
       # format.json { head :no_content }
      #else
       # format.html { render action: "edit" }
       # format.json { render json: @micropost.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private
  def correct_user
    @micropost = current_user.microposts.find_by_id(params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
	  <%= link_to "delete", micropost, method: :delete,
				  data: { confirm: "You sure?" },
				  title: micropost.content %>
  <% end %>

</li>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<li>
  <span class="content"><%= @micropost.content %></span>
  <span class="timestamp">
    Posted <%#= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>